/**
 * Catálogo global de categorías financieras.
 *
 * 20 categorías organizadas en tres bloques: needs, wants, savings.
 * CATEGORIES_CATALOG es un array para permitir iteración y filtrado.
 *
 * Campos de necesidades y ahorro:
 *   factibleMin / factibleMax  — restricciones duras del LP (nunca violadas)
 *   scaling                    — parámetros de escala por ingreso (null si no escala)
 *   lpWeight                   — peso LP para priorización de ahorro (null para necesidades)
 *   alerts                     — umbrales institucionales para diagnóstico (no afectan al LP)
 *
 * Campos de deseos:
 *   ineWeight                  — peso relativo para distribución proporcional INE
 */

export const CATEGORIES_CATALOG = [

  // ═══════════════════════════════════════════════════════════════════════════
  // BLOQUE NECESIDADES
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "housing",
    label: "Vivienda",
    description: "Alquiler o cuota hipotecaria, comunidad, IBI y mantenimiento del hogar",
    block: "needs",
    factibleMin: 0,
    factibleMax: 35,
    scaling: {
      floor: 8,
      exponent: 0.9,
      referenceIncome: 2000,
      useOECD: true,
      bidirectional: false,
    },
    lpWeight: null,
    alerts: {
      mild:   { threshold: 35, message: "Tu gasto en vivienda supera el techo prudencial del Banco de España" },
      severe: { threshold: 40, message: "Tu gasto en vivienda supera el umbral de sobrecarga oficial de la UE (Eurostat)" },
    },
    // Campos heredados — conservados para compatibilidad con flows de diagnóstico
    isAnchor: true,
    isInsurance: false,
    isDebt: false,
    healthyRange: { min: 3, max: 30 },
    alertDirection: "above",
    referenceSource: "Banco de España / Finanzas para Todos / Eurostat EU-SILC",
    referenceReliability: "very_high",
    ineReference: 27.9,
    ineWeight: null,
    examples: ["Alquiler mensual", "Cuota hipotecaria", "Comunidad de propietarios", "IBI", "Seguro del hogar"],
  },

  {
    id: "utilities",
    label: "Suministros",
    description: "Electricidad, gas, agua, internet y telefonía móvil",
    block: "needs",
    factibleMin: 0,
    factibleMax: 15,
    scaling: {
      floor: 1,
      exponent: 0.95,
      referenceIncome: 2000,
      useOECD: false,
      bidirectional: false,
    },
    lpWeight: null,
    alerts: {
      mild:   { threshold: 10, message: "Tu gasto en suministros roza el umbral de pobreza energética de la UE" },
      severe: { threshold: 13, message: "Tu gasto en suministros es excesivo para cualquier perfil" },
    },
    isAnchor: false,
    isInsurance: false,
    isDebt: false,
    healthyRange: { min: 4, max: 10 },
    alertDirection: "above",
    referenceSource: "Directiva UE Eficiencia Energética / Umbral Boardman",
    referenceReliability: "medium",
    ineReference: 6.7,
    ineWeight: null,
    examples: ["Factura de luz", "Factura de gas", "Agua", "Internet", "Teléfono móvil"],
  },

  {
    id: "groceries",
    label: "Alimentación",
    description: "Compra en supermercado y mercado para consumo en el hogar",
    block: "needs",
    factibleMin: 3,
    factibleMax: 25,
    scaling: {
      floor: 1,
      exponent: 0.95,
      referenceIncome: 2000,
      useOECD: false,
      bidirectional: true,
    },
    lpWeight: null,
    alerts: {
      mild:   { threshold: 20, message: "Tu gasto en alimentación supera la media española del INE" },
      severe: { threshold: 25, message: "Tu gasto en alimentación es significativamente elevado" },
    },
    isAnchor: true,
    isInsurance: false,
    isDebt: false,
    healthyRange: { min: 8, max: 20 },
    alertDirection: "above",
    referenceSource: "INE EPF 2024 / BLS Consumer Expenditure Survey",
    referenceReliability: "medium",
    ineReference: 13.6,
    ineWeight: null,
    examples: ["Supermercado", "Mercado", "Carnicería", "Frutería"],
  },

  {
    id: "transport",
    label: "Transporte",
    description: "Transporte público, combustible, mantenimiento del vehículo y seguro",
    block: "needs",
    factibleMin: 0,
    factibleMax: 25,
    scaling: {
      floor: 1,
      exponent: 0.75,
      referenceIncome: 2000,
      useOECD: false,
      bidirectional: false,
    },
    lpWeight: null,
    alerts: {
      mild:   { threshold: 18, message: "Tu gasto en transporte supera el rango habitual" },
      severe: { threshold: 22, message: "Tu gasto en transporte es desproporcionado para cualquier perfil" },
    },
    isAnchor: true,
    isInsurance: false,
    isDebt: false,
    healthyRange: { min: 3, max: 18 },
    alertDirection: "above",
    referenceSource: "INE EPF 2024 / Regla 20/4/10",
    referenceReliability: "medium",
    ineReference: 9.8,
    ineWeight: null,
    examples: ["Abono transporte", "Gasolina", "Seguro del vehículo", "ITV y mantenimiento", "Renting o leasing"],
  },

  {
    id: "health",
    label: "Salud",
    description: "Seguro médico privado, farmacia, dental, óptica y copagos",
    block: "needs",
    factibleMin: 0,
    factibleMax: 15,
    scaling: {
      floor: 1,
      exponent: 0.95,
      referenceIncome: 2000,
      useOECD: false,
      bidirectional: false,
    },
    lpWeight: null,
    alerts: {
      mild:   { threshold: 10, message: "Tu gasto en salud es elevado" },
      severe: { threshold: 13, message: "Tu gasto en salud supera el umbral de dificultad financiera de la OMS" },
    },
    isAnchor: true,
    isInsurance: false,
    isDebt: false,
    healthyRange: { min: 1, max: 10 },
    alertDirection: "above",
    referenceSource: "OMS SDG 3.8.2 / INE EPF 2024",
    referenceReliability: "high",
    ineReference: 3.4,
    ineWeight: null,
    examples: ["Seguro médico privado", "Farmacia", "Dentista", "Óptica", "Copagos médicos"],
  },

  {
    id: "education",
    label: "Educación",
    description: "Matrículas, libros, material escolar, cursos y formación continua",
    block: "needs",
    factibleMin: 0,
    factibleMax: 45,
    scaling: {
      floor: 0,
      exponent: 0.5,
      referenceIncome: 2000,
      useOECD: false,
      bidirectional: false,
    },
    lpWeight: null,
    alerts: {
      mild:   { threshold: 20, message: "Tu gasto en educación es elevado" },
      severe: { threshold: 25, message: "Tu gasto en educación compromete otras categorías esenciales" },
    },
    isAnchor: true,
    isInsurance: false,
    isDebt: false,
    healthyRange: { min: 0, max: 20 },
    alertDirection: "above",
    referenceSource: "INE EPF 2024",
    referenceReliability: "very_low",
    ineReference: 1.4,
    ineWeight: null,
    examples: ["Matrícula universitaria", "Libros de texto", "Cursos de idiomas", "Actividades extraescolares", "Máster o postgrado"],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // BLOQUE DESEOS — los 8 pesos INE suman 101 por redondeo; el motor normaliza
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "dining_out",
    label: "Restaurantes y bares",
    description: "Cenas fuera, cafeterías, bares y comida a domicilio",
    block: "wants",
    factibleMin: null,
    factibleMax: null,
    scaling: null,
    lpWeight: null,
    alerts: null,
    isAnchor: false,
    isInsurance: false,
    isDebt: false,
    healthyRange: { min: 0, max: 15 },
    alertDirection: "above",
    referenceSource: "INE EPF 2024 (descriptivo)",
    referenceReliability: "low",
    ineReference: 4.7,
    ineWeight: 22,
    examples: ["Restaurantes", "Bares y cafeterías", "Delivery y comida a domicilio"],
  },

  {
    id: "travel",
    label: "Viajes y vacaciones",
    description: "Viajes, vacaciones, hoteles y alojamiento turístico",
    block: "wants",
    factibleMin: null,
    factibleMax: null,
    scaling: null,
    lpWeight: null,
    alerts: null,
    isAnchor: false,
    isInsurance: false,
    isDebt: false,
    healthyRange: { min: 0, max: 15 },
    alertDirection: "above",
    referenceSource: "INE EPF 2024 (descriptivo)",
    referenceReliability: "very_low",
    ineReference: 3.8,
    ineWeight: 17,
    examples: ["Vuelos", "Hoteles", "Apartamentos turísticos", "Paquetes vacacionales"],
  },

  {
    id: "clothing",
    label: "Ropa y calzado",
    description: "Ropa, calzado y complementos para toda la familia",
    block: "wants",
    factibleMin: null,
    factibleMax: null,
    scaling: null,
    lpWeight: null,
    alerts: null,
    isAnchor: false,
    isInsurance: false,
    isDebt: false,
    healthyRange: { min: 0, max: 10 },
    alertDirection: "above",
    referenceSource: "INE EPF 2024 (descriptivo)",
    referenceReliability: "low",
    ineReference: 3.4,
    ineWeight: 16,
    examples: ["Ropa", "Calzado", "Accesorios", "Ropa deportiva"],
  },

  {
    id: "personal_care",
    label: "Belleza y cuidado personal",
    description: "Peluquería, cosmética, perfumería y cuidado personal",
    block: "wants",
    factibleMin: null,
    factibleMax: null,
    scaling: null,
    lpWeight: null,
    alerts: null,
    isAnchor: false,
    isInsurance: false,
    isDebt: false,
    healthyRange: { min: 0, max: 10 },
    alertDirection: "above",
    referenceSource: "INE EPF 2024 (descriptivo)",
    referenceReliability: "very_low",
    ineReference: 3.1,
    ineWeight: 14,
    examples: ["Peluquería", "Cosmética y perfumería", "Productos de higiene premium"],
  },

  {
    id: "entertainment",
    label: "Ocio y entretenimiento",
    description: "Cine, teatro, conciertos, eventos y actividades culturales",
    block: "wants",
    factibleMin: null,
    factibleMax: null,
    scaling: null,
    lpWeight: null,
    alerts: null,
    isAnchor: false,
    isInsurance: false,
    isDebt: false,
    healthyRange: { min: 0, max: 10 },
    alertDirection: "above",
    referenceSource: "INE EPF 2024 (descriptivo)",
    referenceReliability: "low",
    ineReference: 2.2,
    ineWeight: 10,
    examples: ["Cine y teatro", "Conciertos", "Museos", "Parques de atracciones"],
  },

  {
    id: "hobbies",
    label: "Hobbies y deporte",
    description: "Equipamiento deportivo, actividades recreativas y aficiones",
    block: "wants",
    factibleMin: null,
    factibleMax: null,
    scaling: null,
    lpWeight: null,
    alerts: null,
    isAnchor: false,
    isInsurance: false,
    isDebt: false,
    healthyRange: { min: 0, max: 10 },
    alertDirection: "above",
    referenceSource: "INE EPF 2024 (descriptivo)",
    referenceReliability: "very_low",
    ineReference: 2.2,
    ineWeight: 10,
    examples: ["Cuota del gimnasio", "Material deportivo", "Equipamiento para hobbies"],
  },

  {
    id: "subscriptions",
    label: "Suscripciones digitales",
    description: "Streaming, aplicaciones, software y servicios digitales",
    block: "wants",
    factibleMin: null,
    factibleMax: null,
    scaling: null,
    lpWeight: null,
    alerts: null,
    isAnchor: false,
    isInsurance: false,
    isDebt: false,
    healthyRange: { min: 0, max: 5 },
    alertDirection: "above",
    referenceSource: "INE EPF 2024 / Deloitte Digital Media Trends (estimado)",
    referenceReliability: "very_low",
    ineReference: 1.3,
    ineWeight: 6,
    examples: ["Netflix, Spotify, Disney+", "Aplicaciones y software", "Servicios en la nube"],
  },

  {
    id: "gifts",
    label: "Regalos y donaciones",
    description: "Regalos, donaciones a ONGs y ayuda a personas del entorno",
    block: "wants",
    factibleMin: null,
    factibleMax: null,
    scaling: null,
    lpWeight: null,
    alerts: null,
    isAnchor: false,
    isInsurance: false,
    isDebt: false,
    healthyRange: { min: 0, max: 5 },
    alertDirection: "above",
    referenceSource: "INE EPF 2024 / Ley 49/2002 (estimado)",
    referenceReliability: "low",
    ineReference: 1.3,
    ineWeight: 6,
    examples: ["Regalos de cumpleaños y navidad", "Donaciones a ONGs", "Ayuda a familia o amigos"],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // BLOQUE AHORRO
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "life_insurance",
    label: "Seguro de vida",
    description: "Prima mensual del seguro de vida o seguro vinculado a hipoteca",
    block: "savings",
    factibleMin: 0,
    factibleMax: 1.5,
    scaling: {
      floor: 0.3,
      exponent: 0.95,
      referenceIncome: 2000,
      useOECD: false,
      bidirectional: false,
    },
    lpWeight: 30,
    alerts: null,
    isAnchor: false,
    isInsurance: true,
    isDebt: false,
    healthyRange: { min: 0.5, max: 3 },
    alertDirection: "above",
    referenceSource: "Charles Schwab / Ramsey Solutions",
    referenceReliability: "low",
    ineReference: null,
    ineWeight: null,
    examples: ["Seguro de vida temporal", "Seguro de vida vinculado a hipoteca"],
  },

  {
    id: "emergency_fund",
    label: "Fondo de emergencia",
    description: "Aportación mensual para alcanzar o mantener el colchón de emergencias",
    block: "savings",
    factibleMin: 0,
    factibleMax: 1,
    scaling: null,
    lpWeight: 50,
    alerts: null,
    isAnchor: true,
    isInsurance: false,
    isDebt: false,
    healthyRange: { min: 1, max: 10 },
    alertDirection: "below",
    referenceSource: "Banco de España / Finanzas para Todos / OCDE",
    referenceReliability: "very_high",
    ineReference: null,
    ineWeight: null,
    examples: ["Cuenta de ahorro líquida", "Depósito a la vista"],
  },

  {
    id: "short_term_savings",
    label: "Ahorro a corto plazo",
    description: "Ahorro para objetivos en menos de 2 años: vacaciones, electrodomésticos, reparaciones",
    block: "savings",
    factibleMin: 0,
    factibleMax: 6,
    scaling: null,
    lpWeight: 15,
    alerts: null,
    isAnchor: false,
    isInsurance: false,
    isDebt: false,
    healthyRange: { min: 2, max: 6 },
    alertDirection: "below",
    referenceSource: "Fidelity 50/15/5",
    referenceReliability: "medium",
    ineReference: null,
    ineWeight: null,
    examples: ["Ahorro para vacaciones", "Fondo para reparaciones del hogar", "Electrónica y electrodomésticos"],
  },

  {
    id: "long_term_savings",
    label: "Ahorro a largo plazo",
    description: "Ahorro para objetivos a más de 2 años, principalmente entrada de vivienda",
    block: "savings",
    factibleMin: 0,
    factibleMax: 12,
    scaling: null,
    lpWeight: 20,
    alerts: null,
    isAnchor: true,
    isInsurance: false,
    isDebt: false,
    healthyRange: { min: 0, max: 15 },
    alertDirection: "below",
    referenceSource: "Banco de España (normativa LTV 80%)",
    referenceReliability: "medium_high",
    ineReference: null,
    ineWeight: null,
    examples: ["Ahorro para entrada de vivienda", "Cuenta ahorro a largo plazo"],
  },

  {
    id: "investment",
    label: "Inversión y jubilación",
    description: "Aportaciones a planes de pensiones, fondos de inversión y otros vehículos a largo plazo",
    block: "savings",
    factibleMin: 0,
    factibleMax: 15,
    scaling: null,
    lpWeight: 40,
    alerts: null,
    isAnchor: true,
    isInsurance: false,
    isDebt: false,
    healthyRange: { min: 4, max: 15 },
    alertDirection: "below",
    referenceSource: "OCDE Pensions at a Glance 2025 / Wade Pfau (JFP 2011)",
    referenceReliability: "medium_high",
    ineReference: null,
    ineWeight: null,
    examples: ["Plan de pensiones", "Fondo de inversión indexado", "ETFs"],
  },

  {
    id: "debt_extra",
    label: "Amortización extra de deuda",
    description: "Pagos adicionales voluntarios para reducir deuda más rápido de lo pactado",
    block: "savings",
    factibleMin: 0,
    factibleMax: 0,
    scaling: null,
    lpWeight: 10,
    alerts: null,
    isAnchor: true,
    isInsurance: false,
    isDebt: true,
    healthyRange: { min: 0, max: 5 },
    alertDirection: "above",
    referenceSource: "Bogleheads (principio financiero)",
    referenceReliability: "medium",
    ineReference: null,
    ineWeight: null,
    examples: ["Amortización anticipada de hipoteca", "Pago adelantado de préstamo personal"],
  },

];

// ─── Vista reducida para Client Components ───────────────────────────────────
// Solo los campos que necesita la UI (sin restricciones LP, alertas ni metadatos
// de calibración). Reduce el peso del bundle enviado al cliente.
export const CATEGORIES_UI = CATEGORIES_CATALOG.map(({ id, label, block, description }) => ({
  id,
  label,
  block,
  description,
}));
